-- Enable output
SET SERVEROUTPUT ON;

-- Create Table
CREATE TABLE employee (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(20),
    LastName VARCHAR2(20),
    Gender CHAR(1),
    DateOfBirth DATE,
    designation VARCHAR2(20),
    DepartmentName VARCHAR2(20),
    Managerid NUMBER,
    JoinedDate DATE,
    Salary NUMBER
);

BEGIN
    DBMS_OUTPUT.PUT_LINE('Employee table created successfully.');
END;
/

-- Insert Records
BEGIN
    INSERT INTO employee 
    (FirstName, LastName, Gender, DateOfBirth, designation, DepartmentName, Managerid, JoinedDate, Salary)
    VALUES ('Swodesh','Singh','M', DATE '2009-03-03','CEO','Headquaters',0, DATE '2000-01-01',1000000);

    INSERT INTO employee 
    (FirstName, LastName, Gender, DateOfBirth, designation, DepartmentName, Managerid, JoinedDate, Salary)
    VALUES ('Ram','Yadav','M', DATE '1999-07-23','employee','software management',1, DATE '2008-11-21',20000);

    INSERT INTO employee 
    (FirstName, LastName, Gender, DateOfBirth, designation, DepartmentName, Managerid, JoinedDate, Salary)
    VALUES ('Adarsha','Chaulagai','M', DATE '1988-03-03','manager','software management',0, DATE '2000-01-01',1000);

    DBMS_OUTPUT.PUT_LINE('Records inserted successfully.');
END;
/

-- Update Record
BEGIN
    UPDATE employee
    SET Gender = 'F'
    WHERE id = 2;

    DBMS_OUTPUT.PUT_LINE('Employee record updated successfully.');
END;
/

-- Display Data
SELECT * FROM employee;